set_property PACKAGE_PIN C9 [get_ports {k_in[0]}]
set_property PACKAGE_PIN B9 [get_ports {k_in[1]}]
set_property PACKAGE_PIN G11 [get_ports {k_in[2]}]
set_property PACKAGE_PIN F10 [get_ports {k_in[3]}]
set_property PACKAGE_PIN D10 [get_ports {k_in[4]}]
set_property PACKAGE_PIN E11 [get_ports {k_in[5]}]
set_property PACKAGE_PIN D11 [get_ports {k_in[6]}]
set_property PACKAGE_PIN A14 [get_ports {k_in[7]}]
set_property PACKAGE_PIN B10 [get_ports {k_in[8]}]
set_property PACKAGE_PIN A10 [get_ports {k_in[9]}]
set_property PACKAGE_PIN B15 [get_ports {k_in[10]}]
set_property PACKAGE_PIN A15 [get_ports {k_in[11]}]
set_property PACKAGE_PIN A13 [get_ports {k_in[12]}]
set_property PACKAGE_PIN A12 [get_ports {k_in[13]}]
set_property PACKAGE_PIN D8 [get_ports {k_in[14]}]
set_property PACKAGE_PIN D9 [get_ports {k_in[15]}]

set_property PACKAGE_PIN B20 [get_ports {seg_sel[0]}]
set_property PACKAGE_PIN C22 [get_ports {seg_sel[1]}]
set_property PACKAGE_PIN D21 [get_ports {seg_sel[2]}]
set_property PACKAGE_PIN C24 [get_ports {seg_sel[3]}]
set_property PACKAGE_PIN B26 [get_ports {seg_sel[4]}]
set_property PACKAGE_PIN B25 [get_ports {seg_sel[5]}]
set_property PACKAGE_PIN L23 [get_ports {seg_sel[6]}]
set_property PACKAGE_PIN K21 [get_ports {seg_sel[7]}]
set_property PACKAGE_PIN H22 [get_ports {seg_sel[8]}]
set_property PACKAGE_PIN J24 [get_ports {seg_sel[9]}]
set_property PACKAGE_PIN J25 [get_ports {seg_sel[10]}]
set_property PACKAGE_PIN A20 [get_ports {seg_sel[11]}]
set_property PACKAGE_PIN C26 [get_ports {seg_sel[12]}]
set_property PACKAGE_PIN D26 [get_ports {seg_sel[13]}]
set_property PACKAGE_PIN A24 [get_ports {seg_sel[14]}]
set_property PACKAGE_PIN A23 [get_ports {seg_sel[15]}]

set_property PACKAGE_PIN J21 [get_ports {seg_data[0]}]
set_property PACKAGE_PIN H24 [get_ports {seg_data[1]}]
set_property PACKAGE_PIN H23 [get_ports {seg_data[2]}]
set_property PACKAGE_PIN G21 [get_ports {seg_data[3]}]
set_property PACKAGE_PIN H21 [get_ports {seg_data[4]}]
set_property PACKAGE_PIN H26 [get_ports {seg_data[5]}]
set_property PACKAGE_PIN J26 [get_ports {seg_data[6]}]
set_property PACKAGE_PIN E26 [get_ports {seg_data[7]}]


set_property PACKAGE_PIN E10 [get_ports clk]
set_property PACKAGE_PIN J8 [get_ports rst]

set_property IOSTANDARD LVCMOS18 [get_ports {k_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[11]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[12]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[13]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[14]}]
set_property IOSTANDARD LVCMOS18 [get_ports {k_in[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_sel[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg_data[7]}]


set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports rst]