//////////////////////////////////////////////////////////////////////////////////////////////
//
// Verilog file generated by X-HDL - Revision 3.2.52  Mar. 28, 2005 
// Fri Mar 16 08:22:26 2012
//
//      Input file         : C:/EDA_FOR_PC_BOOK/CPU8B_PACK/ALU181.vhd
//      Design name        : ALU181
//      Author             : 
//      Company            : 
//
//      Description        : 
//
//
//////////////////////////////////////////////////////////////////////////////////////////////
//
module ALU181 (S, A, B, F, M, CN, CO, FZ);

   input[3:0] S; 
   input[7:0] A; 
   input[7:0] B; 
   output[7:0] F; 
   wire[7:0] F;
   input M; 
   input CN; 
   output CO; 
   wire CO;
   output FZ; 
   reg FZ;

   wire[8:0] A9; 
   wire[8:0] B9; 
   reg[8:0] F9; 

   assign A9 = {1'b0, A} ;
   assign B9 = {1'b0, B} ;

   always @(M or CN or A9 or B9 or S)
   begin
      case (S)
         4'b0000 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 + CN ; 
                     end
                     else
                     begin
                        F9 <= ~A9 ; 
                     end 
                  end
         4'b0001 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | B9) + CN ; 
                     end
                     else
                     begin
                        F9 <= ~(A9 | B9) ; 
                     end 
                  end
         4'b0010 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | (~B9)) + CN ; 
                     end
                     else
                     begin
                        F9 <= (~A9) & B9 ; 
                     end 
                  end
         4'b0011 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= 9'b000000000 - CN ; 
                     end
                     else
                     begin
                        F9 <= 9'b000000000 ; 
                     end 
                  end
         4'b0100 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 + (A9 & ~B9) + CN ; 
                     end
                     else
                     begin
                        F9 <= ~(A9 & B9) ; 
                     end 
                  end
         4'b0101 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | B9) + (A9 & ~B9) + CN ; 
                     end
                     else
                     begin
                        F9 <= ~B9 ; 
                     end 
                  end
         4'b0110 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 - B9 - CN ; 
                     end
                     else
                     begin
                        F9 <= A9 ^ B9 ; 
                     end 
                  end
         4'b0111 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 & (~B9)) - CN ; 
                     end
                     else
                     begin
                        F9 <= A9 & (~B9) ; 
                     end 
                  end
         4'b1000 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 + (A9 & B9) + CN ; 
                     end
                     else
                     begin
                        F9 <= (~A9) | B9 ; 
                     end 
                  end
         4'b1001 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 + B9 + CN ; 
                     end
                     else
                     begin
                        F9 <= ~(A9 ^ B9) ; 
                     end 
                  end
         4'b1010 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | (~B9)) + (A9 & B9) + CN ; 
                     end
                     else
                     begin
                        F9 <= B9 ; 
                     end 
                  end
         4'b1011 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 & B9) - CN ; 
                     end
                     else
                     begin
                        F9 <= A9 & B9 ; 
                     end 
                  end
         4'b1100 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 + A9 + CN ; 
                     end
                     else
                     begin
                        F9 <= 9'b000000001 ; 
                     end 
                  end
         4'b1101 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | B9) + A9 + CN ; 
                     end
                     else
                     begin
                        F9 <= A9 | (~B9) ; 
                     end 
                  end
         4'b1110 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= (A9 | (~B9)) + A9 + CN ; 
                     end
                     else
                     begin
                        F9 <= A9 | B9 ; 
                     end 
                  end
         4'b1111 :
                  begin
                     if (M == 1'b0)
                     begin
                        F9 <= A9 - CN ; 
                     end
                     else
                     begin
                        F9 <= A9 ; 
                     end 
                  end
         default :
                  begin
                     F9 <= 9'b000000000 ; 
                  end
      endcase 
      if (A9 == B9)
      begin
         FZ <= 1'b0 ; 
      end
      else
      begin
         FZ <= 1'b1 ; 
      end 
   end 
   assign F = F9[7:0] ;
   assign CO = F9[8] ;
endmodule
