set_property IOSTANDARD LVCMOS18 [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {data_in[7]}]
set_property PACKAGE_PIN C9 [get_ports {data_in[0]}]
set_property PACKAGE_PIN B9 [get_ports {data_in[1]}]
set_property PACKAGE_PIN G11 [get_ports {data_in[2]}]
set_property PACKAGE_PIN F10 [get_ports {data_in[3]}]
set_property PACKAGE_PIN D10 [get_ports {data_in[4]}]
set_property PACKAGE_PIN E11 [get_ports {data_in[5]}]
set_property PACKAGE_PIN D11 [get_ports {data_in[6]}]
set_property PACKAGE_PIN A14 [get_ports {data_in[7]}]

set_property PACKAGE_PIN E10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

#sw31
set_property PACKAGE_PIN J8 [get_ports rst]
set_property IOSTANDARD LVCMOS18 [get_ports rst]
#sw30
set_property PACKAGE_PIN J14 [get_ports key_in]
set_property IOSTANDARD LVCMOS18 [get_ports key_in]
#sw29
set_property PACKAGE_PIN H9 [get_ports wr]
set_property IOSTANDARD LVCMOS18 [get_ports wr]
#sw28
set_property PACKAGE_PIN H8 [get_ports rd]
set_property IOSTANDARD LVCMOS18 [get_ports rd]
#led15
set_property PACKAGE_PIN L20 [get_ports empty]
set_property IOSTANDARD LVCMOS33 [get_ports empty]
#led11
set_property PACKAGE_PIN J20 [get_ports full]
set_property IOSTANDARD LVCMOS33 [get_ports full]
#led0-7
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[0]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[7]}]
set_property PACKAGE_PIN G16			[get_ports {data_out[0]}]
set_property PACKAGE_PIN H16 			[get_ports {data_out[1]}]
set_property PACKAGE_PIN D16 			[get_ports {data_out[2]}]
set_property PACKAGE_PIN D15 			[get_ports {data_out[3]}]
set_property PACKAGE_PIN C18 			[get_ports {data_out[4]}]
set_property PACKAGE_PIN C17 			[get_ports {data_out[5]}]
set_property PACKAGE_PIN B19 			[get_ports {data_out[6]}]
set_property PACKAGE_PIN C19 			[get_ports {data_out[7]}]