set_property SEVERITY {Warning} [get_drc_checks LUTLP-1]
set_property ALLOW_COMBINATORIAL_LOOPS TRUE

set_property IOSTANDARD LVCMOS33 [get_ports {segData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segData[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segSel[0]}]


set_property PACKAGE_PIN B20 [get_ports segSel[0]]
set_property PACKAGE_PIN C22 [get_ports segSel[1]]
set_property PACKAGE_PIN D21 [get_ports segSel[2]]
set_property PACKAGE_PIN C24 [get_ports segSel[3]]
set_property PACKAGE_PIN B26 [get_ports segSel[4]]
set_property PACKAGE_PIN B25 [get_ports segSel[5]]
set_property PACKAGE_PIN L23 [get_ports segSel[6]]
set_property PACKAGE_PIN K21 [get_ports segSel[7]]
set_property PACKAGE_PIN H22 [get_ports segSel[8]]
set_property PACKAGE_PIN J24 [get_ports segSel[9]]
set_property PACKAGE_PIN J25 [get_ports segSel[10]]
set_property PACKAGE_PIN A20 [get_ports segSel[11]]
set_property PACKAGE_PIN C26 [get_ports segSel[12]]
set_property PACKAGE_PIN D26 [get_ports segSel[13]]
set_property PACKAGE_PIN A24 [get_ports segSel[14]]
set_property PACKAGE_PIN A23 [get_ports segSel[15]]
set_property PACKAGE_PIN E26 [get_ports segData[0]]
set_property PACKAGE_PIN J26 [get_ports segData[1]]
set_property PACKAGE_PIN H26 [get_ports segData[2]]
set_property PACKAGE_PIN H21 [get_ports segData[3]]
set_property PACKAGE_PIN G21 [get_ports segData[4]]
set_property PACKAGE_PIN H23 [get_ports segData[5]]
set_property PACKAGE_PIN H24 [get_ports segData[6]]
set_property PACKAGE_PIN J21 [get_ports segData[7]]

set_property PACKAGE_PIN E10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports {clk}]

set_property PACKAGE_PIN C9 [get_ports n_rst]
set_property IOSTANDARD LVCMOS18 [get_ports {n_rst}]

set_property PACKAGE_PIN B9 [get_ports n_ld]
set_property IOSTANDARD LVCMOS18 [get_ports {n_ld}]

set_property PACKAGE_PIN G11 [get_ports m_pc]
set_property IOSTANDARD LVCMOS18 [get_ports {m_pc}]

set_property PACKAGE_PIN F10 [get_ports nPCH]
set_property IOSTANDARD LVCMOS18 [get_ports {nPCH}]

set_property PACKAGE_PIN D10 [get_ports nPCL]
set_property IOSTANDARD LVCMOS18 [get_ports {nPCL}]

set_property PACKAGE_PIN F8 [get_ports PC_in[0]]
set_property PACKAGE_PIN F9 [get_ports PC_in[1]]
set_property PACKAGE_PIN H11 [get_ports PC_in[2]]
set_property PACKAGE_PIN H12 [get_ports PC_in[3]]
set_property PACKAGE_PIN G14 [get_ports PC_in[4]]
set_property PACKAGE_PIN J10 [get_ports PC_in[5]]
set_property PACKAGE_PIN H14 [get_ports PC_in[6]]
set_property PACKAGE_PIN J11 [get_ports PC_in[7]]
set_property PACKAGE_PIN H13 [get_ports PC_in[8]]
set_property PACKAGE_PIN J13 [get_ports PC_in[9]]
set_property PACKAGE_PIN G9 [get_ports PC_in[10]]
set_property PACKAGE_PIN G10 [get_ports PC_in[11]]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[8]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[9]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[10]}]
set_property IOSTANDARD LVCMOS18 [get_ports {PC_in[11]}]