#SEG_DIG1~16
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[15]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[14]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[13]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[12]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[11]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[10]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[9]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[8]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_dig[0]}]
set_property PACKAGE_PIN A23        [get_ports {seg_dig[15]}]
set_property PACKAGE_PIN A24        [get_ports {seg_dig[14]}]
set_property PACKAGE_PIN D26        [get_ports {seg_dig[13]}]
set_property PACKAGE_PIN C26        [get_ports {seg_dig[12]}]
set_property PACKAGE_PIN A20        [get_ports {seg_dig[11]}]
set_property PACKAGE_PIN J25        [get_ports {seg_dig[10]}]
set_property PACKAGE_PIN J24        [get_ports {seg_dig[9]}]
set_property PACKAGE_PIN H22        [get_ports {seg_dig[8]}]
set_property PACKAGE_PIN K21        [get_ports {seg_dig[7]}]
set_property PACKAGE_PIN L23        [get_ports {seg_dig[6]}]
set_property PACKAGE_PIN B25        [get_ports {seg_dig[5]}]
set_property PACKAGE_PIN B26        [get_ports {seg_dig[4]}]
set_property PACKAGE_PIN C24        [get_ports {seg_dig[3]}]
set_property PACKAGE_PIN D21        [get_ports {seg_dig[2]}]
set_property PACKAGE_PIN C22        [get_ports {seg_dig[1]}]
set_property PACKAGE_PIN B20        [get_ports {seg_dig[0]}]

#seg_data
set_property PACKAGE_PIN E26        [get_ports {seg_data[7]}]
set_property PACKAGE_PIN J26        [get_ports {seg_data[6]}]
set_property PACKAGE_PIN H26        [get_ports {seg_data[5]}]
set_property PACKAGE_PIN H21        [get_ports {seg_data[4]}]
set_property PACKAGE_PIN G21        [get_ports {seg_data[3]}]
set_property PACKAGE_PIN H23        [get_ports {seg_data[2]}]
set_property PACKAGE_PIN H24        [get_ports {seg_data[1]}]
set_property PACKAGE_PIN J21        [get_ports {seg_data[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[7]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[6]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[5]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[4]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[3]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[2]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {seg_data[0]}]

#sw31~24
set_property PACKAGE_PIN J8         [get_ports rst]
set_property IOSTANDARD LVCMOS18    [get_ports rst]
set_property PACKAGE_PIN J14        [get_ports LD_IR1]
set_property IOSTANDARD LVCMOS18    [get_ports LD_IR1]
set_property PACKAGE_PIN H9         [get_ports LD_IR2]
set_property IOSTANDARD LVCMOS18    [get_ports LD_IR2]
set_property PACKAGE_PIN H8         [get_ports LD_IR3]
set_property IOSTANDARD LVCMOS18    [get_ports LD_IR3]
set_property PACKAGE_PIN G10        [get_ports nARen]
set_property IOSTANDARD LVCMOS18    [get_ports nARen]

#CLK_100M
set_property PACKAGE_PIN E10        [get_ports clk_IR]
set_property IOSTANDARD LVCMOS18    [get_ports clk_IR]

#LED0~1
set_property IOSTANDARD LVCMOS33 		[get_ports RS]
set_property IOSTANDARD LVCMOS33 		[get_ports RD]
set_property PACKAGE_PIN G16			[get_ports RS]
set_property PACKAGE_PIN H16 			[get_ports RD]

#SW0~15
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[7]}]
set_property PACKAGE_PIN C9         [get_ports {data_in[0]}]
set_property PACKAGE_PIN B9         [get_ports {data_in[1]}]
set_property PACKAGE_PIN G11        [get_ports {data_in[2]}]
set_property PACKAGE_PIN F10        [get_ports {data_in[3]}]
set_property PACKAGE_PIN D10        [get_ports {data_in[4]}]
set_property PACKAGE_PIN E11        [get_ports {data_in[5]}]
set_property PACKAGE_PIN D11        [get_ports {data_in[6]}]
set_property PACKAGE_PIN A14        [get_ports {data_in[7]}]