set_property IOSTANDARD LVCMOS33    [get_ports OE]
set_property IOSTANDARD LVCMOS33    [get_ports {X[0]}]
set_property IOSTANDARD LVCMOS33    [get_ports {X[1]}]
set_property IOSTANDARD LVCMOS33    [get_ports {X[2]}]

set_property PACKAGE_PIN C9         [get_ports OE]
set_property PACKAGE_PIN B9         [get_ports {X[0]}]
set_property PACKAGE_PIN G11        [get_ports {X[1]}]
set_property PACKAGE_PIN F10        [get_ports {X[2]}]

set_property IOSTANDARD LVCMOS33 		[get_ports {Y[0]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[1]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[2]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[3]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[4]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[5]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[6]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {Y[7]}]
set_property PACKAGE_PIN G16			[get_ports {Y[0]}]
set_property PACKAGE_PIN H16 			[get_ports {Y[1]}]
set_property PACKAGE_PIN D16 			[get_ports {Y[2]}]
set_property PACKAGE_PIN D15 			[get_ports {Y[3]}]
set_property PACKAGE_PIN C18 			[get_ports {Y[4]}]
set_property PACKAGE_PIN C17 			[get_ports {Y[5]}]
set_property PACKAGE_PIN B19 			[get_ports {Y[6]}]
set_property PACKAGE_PIN C19 			[get_ports {Y[7]}]