#clk
set_property PACKAGE_PIN E10 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports clk]

#sw31~28
set_property PACKAGE_PIN J8 [get_ports nreset]
set_property IOSTANDARD LVCMOS18 [get_ports nreset]
set_property PACKAGE_PIN J14        [get_ports SP_CS]
set_property IOSTANDARD LVCMOS18    [get_ports SP_CS]
set_property PACKAGE_PIN H9         [get_ports key_in]
set_property IOSTANDARD LVCMOS18    [get_ports key_in]
set_property PACKAGE_PIN H8         [get_ports nSP_EN]
set_property IOSTANDARD LVCMOS18    [get_ports nSP_EN]
set_property PACKAGE_PIN G10        [get_ports SP_UP ]
set_property IOSTANDARD LVCMOS18    [get_ports SP_UP ]
set_property PACKAGE_PIN G9         [get_ports SP_DN ]
set_property IOSTANDARD LVCMOS18    [get_ports SP_DN ]

#LED0~6
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[0]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[1]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[2]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[3]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[4]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[5]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {AR[6]}]
set_property PACKAGE_PIN G16			[get_ports {AR[0]}]
set_property PACKAGE_PIN H16 			[get_ports {AR[1]}]
set_property PACKAGE_PIN D16 			[get_ports {AR[2]}]
set_property PACKAGE_PIN D15 			[get_ports {AR[3]}]
set_property PACKAGE_PIN C18 			[get_ports {AR[4]}]
set_property PACKAGE_PIN C17 			[get_ports {AR[5]}]
set_property PACKAGE_PIN B19 			[get_ports {AR[6]}]

#SW0~7
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[4]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[5]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[6]}]
set_property IOSTANDARD LVCMOS18    [get_ports {DATA_BUS[7]}]
set_property PACKAGE_PIN C9         [get_ports {DATA_BUS[0]}]
set_property PACKAGE_PIN B9         [get_ports {DATA_BUS[1]}]
set_property PACKAGE_PIN G11        [get_ports {DATA_BUS[2]}]
set_property PACKAGE_PIN F10        [get_ports {DATA_BUS[3]}]
set_property PACKAGE_PIN D10        [get_ports {DATA_BUS[4]}]
set_property PACKAGE_PIN E11        [get_ports {DATA_BUS[5]}]
set_property PACKAGE_PIN D11        [get_ports {DATA_BUS[6]}]
set_property PACKAGE_PIN A14        [get_ports {DATA_BUS[7]}]