@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Fri Apr 22 15:32:51 +0800 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 8261f7dce2ba417890d07e4b512cbc14 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_booth_multiplier_behav xil_defaultlib.tb_booth_multiplier -log elaborate.log"
call xelab  -wto 8261f7dce2ba417890d07e4b512cbc14 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_booth_multiplier_behav xil_defaultlib.tb_booth_multiplier -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
