#SW0~15
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[1]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[2]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[3]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[4]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[5]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[6]}]
set_property IOSTANDARD LVCMOS18    [get_ports {data_in[7]}]
set_property PACKAGE_PIN C9         [get_ports {data_in[0]}]
set_property PACKAGE_PIN B9         [get_ports {data_in[1]}]
set_property PACKAGE_PIN G11        [get_ports {data_in[2]}]
set_property PACKAGE_PIN F10        [get_ports {data_in[3]}]
set_property PACKAGE_PIN D10        [get_ports {data_in[4]}]
set_property PACKAGE_PIN E11        [get_ports {data_in[5]}]
set_property PACKAGE_PIN D11        [get_ports {data_in[6]}]
set_property PACKAGE_PIN A14        [get_ports {data_in[7]}]

#LED
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[0]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[1]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[2]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[3]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[4]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[5]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[6]}]
set_property IOSTANDARD LVCMOS33 		[get_ports {data_out[7]}]
set_property PACKAGE_PIN G16			[get_ports {data_out[0]}]
set_property PACKAGE_PIN H16 			[get_ports {data_out[1]}]
set_property PACKAGE_PIN D16 			[get_ports {data_out[2]}]
set_property PACKAGE_PIN D15 			[get_ports {data_out[3]}]
set_property PACKAGE_PIN C18 			[get_ports {data_out[4]}]
set_property PACKAGE_PIN C17 			[get_ports {data_out[5]}]
set_property PACKAGE_PIN B19 			[get_ports {data_out[6]}]
set_property PACKAGE_PIN C19 			[get_ports {data_out[7]}]

#CLK_100M
set_property PACKAGE_PIN E10        [get_ports clk_RN]
set_property IOSTANDARD LVCMOS18    [get_ports clk_RN]

#sw31~24
set_property PACKAGE_PIN J8         [get_ports Ri_EN]
set_property IOSTANDARD LVCMOS18    [get_ports Ri_EN]
set_property PACKAGE_PIN J14        [get_ports RDRi]
set_property IOSTANDARD LVCMOS18    [get_ports RDRi]
set_property PACKAGE_PIN H9         [get_ports WRRi]
set_property IOSTANDARD LVCMOS18    [get_ports WRRi]
set_property PACKAGE_PIN H8         [get_ports {RS[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {RS[0]}]
set_property PACKAGE_PIN G10        [get_ports {RD[0]}]
set_property IOSTANDARD LVCMOS18    [get_ports {RD[0]}]